version: "3.9"

services: 
    web:
        build: .
        command: daphne -b 127.0.0.1 -p 8080 ChatApp.asgi:application
        volumes: 
            - .:/project
        ports: 
            - 8888:8080
    #     depends_on: 
    #         - db
    # db:
    #     image: postgres
    #     volumes: 
    #         - ./data/database:/var/lib/postgresql/data
    #     environment: 
    #         - POSTGRES_DB=chatapp
    #         - POSTGRES_USER=amangrg
    #         - POSTGRES_PASSWORD=amangrg123
