version: "3.9"

services:           
    app:
        build: .
        command: daphne -b 0.0.0.0 -p 8000 ChatApp.asgi:application
        volumes:
            - .:/project
        ports:
            - "8000:8000"