version: "3.9"

# services: 
#     web:
#         build: .
#         command: daphne -b 127.0.0.1 -p 8000 ChatApp.asgi:application
#         volumes: 
#             - .:/project
#         ports: 
#             - 8888:8000
#         depends_on: 
#             - db
    # db:
    #     image: postgres
    #     volumes: 
    #         - ./data/database:/var/lib/postgresql/data
    #     environment: 
    #         - POSTGRES_DB=chatapp
    #         - POSTGRES_USER=amangrg
    #         - POSTGRES_PASSWORD=amangrg123

services:
    redis:
        image: redis
        command: redis-server
        ports:
            - '6379:6379'
            
    web:
        build: .
        # command: gunicorn
      command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/project
        ports:
            - "8000:8000"
        depends_on: 
            - db
    channels:
        build: .
        command: daphne -b 0.0.0.0 -p 8001 ChatApp.asgi:application
        volumes:
            - .:/project
        ports:
            - "8001:8001"
        links:
            - redis

    db:
        image: postgres
        volumes: 
            - ./data/database:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=chatapp
            - POSTGRES_USER=amangrg
            - POSTGRES_PASSWORD=amangrg123