# Generated by Django 3.1.7 on 2021-05-21 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210512_0607'),
        ('main', '0002_auto_20210520_0433'),
    ]

    operations = [
    ]
